apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-app
  namespace: my-app
spec:
  releaseName: my-app
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "21.1.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: my-app
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: false
