apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: my-app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: my-app-nginx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-nginx
                port:
                  number: 80
