apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  # Increase the number of workers and limits
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=10
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=5s
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|source-controller)"
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  limits:
                    cpu: 2000m
                    memory: 2Gi
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|source-controller)"
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                resources:
                  limits:
                    memory: 2Gi
    target:
      kind: Deployment
      name: image-automation-controller
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          metadata:
            annotations:
              ad.datadoghq.com/manager.checks: |
                {
                  "openmetrics": {
                    "instances": [
                      {
                        "openmetrics_endpoint": "http://%%host%%:%%port_http-prom%%/metrics",
                        "namespace": "fluxcd",
                        "metrics": [
                          {"gotk_reconcile_condition": "gotk.reconcile.condition"},
                          {"gotk_suspend_status": "gotk.suspend.status"},
                          {"gotk_reconcile_duration_seconds": "gotk.reconcile.duration.seconds"},
                          {"controller_runtime_active_workers": "controller.runtime.active.workers"},
                          {"controller_runtime_reconcile": "controller.runtime.reconcile"},
                          {"controller_runtime_reconcile_time_seconds": "controller.runtime.reconcile.time.seconds"},
                          {"controller_runtime_max_concurrent_reconciles": "controller.runtime.max.concurrent.reconciles"},
                          {"controller_runtime_reconcile_errors": "controller.runtime.reconcile.errors"}
                        ],
                        "rename_labels": {
                          "name": "object_name"
                        }
                      }
                    ]
                  }
                }
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/part-of=flux"